name: memory
version: 0.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dev_dependencies:
  ffigen: ^11.0.0

dependencies:
  ffi: ^2.1.0
  core:
    path:
      ../../core/dart

ffigen:
  name: "MemoryBindings"
  ffi-native:
    assetId: "memory-bindings"
  description: "Bindings for memory"
  output: "lib/memory/bindings.dart"
  compiler-opts:
    - "-I../native/include"
  headers:
    entry-points:
      - "../native/memory_dart.h"
      - "../native/tuple_dart.h"
  globals:
    exclude:
      - "(.*)"
  macros:
    exclude:
      - "(.*)"
  typedefs:
    exclude:
      - "_(.*)"
  functions:
    leaf:
      include:
        - "memory_dart_.*"
        - "tuple_dart_.*"
    exclude:
      - "_(.*)"
  structs:
    exclude:
      - "_(.*)"
      - "max_align_t"
      - "file_(.*)"
