name: transport
publish_to: none
version: 0.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  ffi: ^2.1.0
  core:
    path: ../../core/dart
  memory:
    path: ../../memory/dart
  executor:
    path: ../../executor/dart
