name: transport
publish_to: none
version: 0.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dev_dependencies:
  ffigen: ^11.0.0
  test: ^1.24.6

dependencies:
  ffi: ^2.1.0
  core:
    path: ../../core/dart
  memory:
    path: ../../memory/dart
  interactor:
    path: ../../interactor/dart

ffigen:
  name: "TransportBindings"
  ffi-native:
    assetId: "transport-bindings"
  description: "Bindings for Transport"
  output: "lib/transport/bindings.dart"
  headers:
    entry-points:
      - "../native/transport.h"
      - "../native/transport_constants.h"
      - "../native/transport_server.h"
      - "../native/transport_client.h"
      - "../native/transport_file.h"
      - "../native/transport_socket.h"
  globals:
    exclude:
      - "_(.*)"
  functions:
    leaf:
      include:
        - "transport_.*"
    symbol-address:
      include:
        - ".*"
    exclude:
      - "_(.*)"
  macros:
    exclude:
      - "_(.*)"
      - "true"
      - "false"
  typedefs:
    exclude:
      - "_(.*)"
  structs:
    exclude:
      - "_(.*)"
      - "max_align_t"
      - "file_(.*)"
  type-map:
    structs:
      "interactor_completion_event":
        lib: "interactor"
        c-type: "interactor_completion_event"
        dart-type: "interactor_completion_event"
      "iovec":
        lib: "memory"
        c-type: "iovec"
        dart-type: "iovec"
  library-imports:
    interactor: package:interactor/interactor.dart
    memory: package:memory/memory.dart
