// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_field
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<sched_param>)>(
    symbol: 'sched_setparam', assetId: 'mediator-bindings')
external int sched_setparam(
  int __pid,
  ffi.Pointer<sched_param> __param,
);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<sched_param>)>(
    symbol: 'sched_getparam', assetId: 'mediator-bindings')
external int sched_getparam(
  int __pid,
  ffi.Pointer<sched_param> __param,
);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int, ffi.Pointer<sched_param>)>(
    symbol: 'sched_setscheduler', assetId: 'mediator-bindings')
external int sched_setscheduler(
  int __pid,
  int __policy,
  ffi.Pointer<sched_param> __param,
);

@ffi.Native<ffi.Int Function(ffi.Int)>(
    symbol: 'sched_getscheduler', assetId: 'mediator-bindings')
external int sched_getscheduler(
  int __pid,
);

@ffi.Native<ffi.Int Function()>(
    symbol: 'sched_yield', assetId: 'mediator-bindings')
external int sched_yield();

@ffi.Native<ffi.Int Function(ffi.Int)>(
    symbol: 'sched_get_priority_max', assetId: 'mediator-bindings')
external int sched_get_priority_max(
  int __algorithm,
);

@ffi.Native<ffi.Int Function(ffi.Int)>(
    symbol: 'sched_get_priority_min', assetId: 'mediator-bindings')
external int sched_get_priority_min(
  int __algorithm,
);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<timespec>)>(
    symbol: 'sched_rr_get_interval', assetId: 'mediator-bindings')
external int sched_rr_get_interval(
  int __pid,
  ffi.Pointer<timespec> __t,
);

@ffi.Native<clock_t Function()>(symbol: 'clock', assetId: 'mediator-bindings')
external int clock();

@ffi.Native<time_t Function(ffi.Pointer<time_t>)>(
    symbol: 'time', assetId: 'mediator-bindings')
external int time(
  ffi.Pointer<time_t> __timer,
);

@ffi.Native<ffi.Double Function(time_t, time_t)>(
    symbol: 'difftime', assetId: 'mediator-bindings')
external double difftime(
  int __time1,
  int __time0,
);

@ffi.Native<time_t Function(ffi.Pointer<tm>)>(
    symbol: 'mktime', assetId: 'mediator-bindings')
external int mktime(
  ffi.Pointer<tm> __tp,
);

@ffi.Native<
    ffi.Size Function(ffi.Pointer<ffi.Char>, ffi.Size, ffi.Pointer<ffi.Char>,
        ffi.Pointer<tm>)>(symbol: 'strftime', assetId: 'mediator-bindings')
external int strftime(
  ffi.Pointer<ffi.Char> __s,
  int __maxsize,
  ffi.Pointer<ffi.Char> __format,
  ffi.Pointer<tm> __tp,
);

@ffi.Native<
    ffi.Size Function(
        ffi.Pointer<ffi.Char>,
        ffi.Size,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<tm>,
        locale_t)>(symbol: 'strftime_l', assetId: 'mediator-bindings')
external int strftime_l(
  ffi.Pointer<ffi.Char> __s,
  int __maxsize,
  ffi.Pointer<ffi.Char> __format,
  ffi.Pointer<tm> __tp,
  locale_t __loc,
);

@ffi.Native<ffi.Pointer<tm> Function(ffi.Pointer<time_t>)>(
    symbol: 'gmtime', assetId: 'mediator-bindings')
external ffi.Pointer<tm> gmtime(
  ffi.Pointer<time_t> __timer,
);

@ffi.Native<ffi.Pointer<tm> Function(ffi.Pointer<time_t>)>(
    symbol: 'localtime', assetId: 'mediator-bindings')
external ffi.Pointer<tm> localtime(
  ffi.Pointer<time_t> __timer,
);

@ffi.Native<ffi.Pointer<tm> Function(ffi.Pointer<time_t>, ffi.Pointer<tm>)>(
    symbol: 'gmtime_r', assetId: 'mediator-bindings')
external ffi.Pointer<tm> gmtime_r(
  ffi.Pointer<time_t> __timer,
  ffi.Pointer<tm> __tp,
);

@ffi.Native<ffi.Pointer<tm> Function(ffi.Pointer<time_t>, ffi.Pointer<tm>)>(
    symbol: 'localtime_r', assetId: 'mediator-bindings')
external ffi.Pointer<tm> localtime_r(
  ffi.Pointer<time_t> __timer,
  ffi.Pointer<tm> __tp,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<tm>)>(
    symbol: 'asctime', assetId: 'mediator-bindings')
external ffi.Pointer<ffi.Char> asctime(
  ffi.Pointer<tm> __tp,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<time_t>)>(
    symbol: 'ctime', assetId: 'mediator-bindings')
external ffi.Pointer<ffi.Char> ctime(
  ffi.Pointer<time_t> __timer,
);

@ffi.Native<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<tm>, ffi.Pointer<ffi.Char>)>(
    symbol: 'asctime_r', assetId: 'mediator-bindings')
external ffi.Pointer<ffi.Char> asctime_r(
  ffi.Pointer<tm> __tp,
  ffi.Pointer<ffi.Char> __buf,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(ffi.Pointer<time_t>,
        ffi.Pointer<ffi.Char>)>(symbol: 'ctime_r', assetId: 'mediator-bindings')
external ffi.Pointer<ffi.Char> ctime_r(
  ffi.Pointer<time_t> __timer,
  ffi.Pointer<ffi.Char> __buf,
);

@ffi.Native<ffi.Void Function()>(symbol: 'tzset', assetId: 'mediator-bindings')
external void tzset();

@ffi.Native<time_t Function(ffi.Pointer<tm>)>(
    symbol: 'timegm', assetId: 'mediator-bindings')
external int timegm(
  ffi.Pointer<tm> __tp,
);

@ffi.Native<time_t Function(ffi.Pointer<tm>)>(
    symbol: 'timelocal', assetId: 'mediator-bindings')
external int timelocal(
  ffi.Pointer<tm> __tp,
);

@ffi.Native<ffi.Int Function(ffi.Int)>(
    symbol: 'dysize', assetId: 'mediator-bindings')
external int dysize(
  int __year,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<timespec>, ffi.Pointer<timespec>)>(
    symbol: 'nanosleep', assetId: 'mediator-bindings')
external int nanosleep(
  ffi.Pointer<timespec> __requested_time,
  ffi.Pointer<timespec> __remaining,
);

@ffi.Native<ffi.Int Function(clockid_t, ffi.Pointer<timespec>)>(
    symbol: 'clock_getres', assetId: 'mediator-bindings')
external int clock_getres(
  int __clock_id,
  ffi.Pointer<timespec> __res,
);

@ffi.Native<ffi.Int Function(clockid_t, ffi.Pointer<timespec>)>(
    symbol: 'clock_gettime', assetId: 'mediator-bindings')
external int clock_gettime(
  int __clock_id,
  ffi.Pointer<timespec> __tp,
);

@ffi.Native<ffi.Int Function(clockid_t, ffi.Pointer<timespec>)>(
    symbol: 'clock_settime', assetId: 'mediator-bindings')
external int clock_settime(
  int __clock_id,
  ffi.Pointer<timespec> __tp,
);

@ffi.Native<
        ffi.Int Function(
            clockid_t, ffi.Int, ffi.Pointer<timespec>, ffi.Pointer<timespec>)>(
    symbol: 'clock_nanosleep', assetId: 'mediator-bindings')
external int clock_nanosleep(
  int __clock_id,
  int __flags,
  ffi.Pointer<timespec> __req,
  ffi.Pointer<timespec> __rem,
);

@ffi.Native<ffi.Int Function(pid_t, ffi.Pointer<clockid_t>)>(
    symbol: 'clock_getcpuclockid', assetId: 'mediator-bindings')
external int clock_getcpuclockid(
  int __pid,
  ffi.Pointer<clockid_t> __clock_id,
);

@ffi.Native<
        ffi.Int Function(
            clockid_t, ffi.Pointer<sigevent>, ffi.Pointer<timer_t>)>(
    symbol: 'timer_create', assetId: 'mediator-bindings')
external int timer_create(
  int __clock_id,
  ffi.Pointer<sigevent> __evp,
  ffi.Pointer<timer_t> __timerid,
);

@ffi.Native<ffi.Int Function(timer_t)>(
    symbol: 'timer_delete', assetId: 'mediator-bindings')
external int timer_delete(
  timer_t __timerid,
);

@ffi.Native<
        ffi.Int Function(timer_t, ffi.Int, ffi.Pointer<itimerspec>,
            ffi.Pointer<itimerspec>)>(
    symbol: 'timer_settime', assetId: 'mediator-bindings')
external int timer_settime(
  timer_t __timerid,
  int __flags,
  ffi.Pointer<itimerspec> __value,
  ffi.Pointer<itimerspec> __ovalue,
);

@ffi.Native<ffi.Int Function(timer_t, ffi.Pointer<itimerspec>)>(
    symbol: 'timer_gettime', assetId: 'mediator-bindings')
external int timer_gettime(
  timer_t __timerid,
  ffi.Pointer<itimerspec> __value,
);

@ffi.Native<ffi.Int Function(timer_t)>(
    symbol: 'timer_getoverrun', assetId: 'mediator-bindings')
external int timer_getoverrun(
  timer_t __timerid,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<timespec>, ffi.Int)>(
    symbol: 'timespec_get', assetId: 'mediator-bindings')
external int timespec_get(
  ffi.Pointer<timespec> __ts,
  int __base,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_t>,
            ffi.Pointer<pthread_attr_t>,
            ffi.Pointer<
                ffi.NativeFunction<
                    ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>>,
            ffi.Pointer<ffi.Void>)>(
    symbol: 'pthread_create', assetId: 'mediator-bindings')
external int pthread_create(
  ffi.Pointer<pthread_t> __newthread,
  ffi.Pointer<pthread_attr_t> __attr,
  ffi.Pointer<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>>
      __start_routine,
  ffi.Pointer<ffi.Void> __arg,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(
    symbol: 'pthread_exit', assetId: 'mediator-bindings')
external void pthread_exit(
  ffi.Pointer<ffi.Void> __retval,
);

@ffi.Native<ffi.Int Function(pthread_t, ffi.Pointer<ffi.Pointer<ffi.Void>>)>(
    symbol: 'pthread_join', assetId: 'mediator-bindings')
external int pthread_join(
  int __th,
  ffi.Pointer<ffi.Pointer<ffi.Void>> __thread_return,
);

@ffi.Native<ffi.Int Function(pthread_t)>(
    symbol: 'pthread_detach', assetId: 'mediator-bindings')
external int pthread_detach(
  int __th,
);

@ffi.Native<pthread_t Function()>(
    symbol: 'pthread_self', assetId: 'mediator-bindings')
external int pthread_self();

@ffi.Native<ffi.Int Function(pthread_t, pthread_t)>(
    symbol: 'pthread_equal', assetId: 'mediator-bindings')
external int pthread_equal(
  int __thread1,
  int __thread2,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_attr_t>)>(
    symbol: 'pthread_attr_init', assetId: 'mediator-bindings')
external int pthread_attr_init(
  ffi.Pointer<pthread_attr_t> __attr,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_attr_t>)>(
    symbol: 'pthread_attr_destroy', assetId: 'mediator-bindings')
external int pthread_attr_destroy(
  ffi.Pointer<pthread_attr_t> __attr,
);

@ffi.Native<
        ffi.Int Function(ffi.Pointer<pthread_attr_t>, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_attr_getdetachstate', assetId: 'mediator-bindings')
external int pthread_attr_getdetachstate(
  ffi.Pointer<pthread_attr_t> __attr,
  ffi.Pointer<ffi.Int> __detachstate,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_attr_t>, ffi.Int)>(
    symbol: 'pthread_attr_setdetachstate', assetId: 'mediator-bindings')
external int pthread_attr_setdetachstate(
  ffi.Pointer<pthread_attr_t> __attr,
  int __detachstate,
);

@ffi.Native<
        ffi.Int Function(ffi.Pointer<pthread_attr_t>, ffi.Pointer<ffi.Size>)>(
    symbol: 'pthread_attr_getguardsize', assetId: 'mediator-bindings')
external int pthread_attr_getguardsize(
  ffi.Pointer<pthread_attr_t> __attr,
  ffi.Pointer<ffi.Size> __guardsize,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_attr_t>, ffi.Size)>(
    symbol: 'pthread_attr_setguardsize', assetId: 'mediator-bindings')
external int pthread_attr_setguardsize(
  ffi.Pointer<pthread_attr_t> __attr,
  int __guardsize,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_attr_t>, ffi.Pointer<sched_param>)>(
    symbol: 'pthread_attr_getschedparam', assetId: 'mediator-bindings')
external int pthread_attr_getschedparam(
  ffi.Pointer<pthread_attr_t> __attr,
  ffi.Pointer<sched_param> __param,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_attr_t>, ffi.Pointer<sched_param>)>(
    symbol: 'pthread_attr_setschedparam', assetId: 'mediator-bindings')
external int pthread_attr_setschedparam(
  ffi.Pointer<pthread_attr_t> __attr,
  ffi.Pointer<sched_param> __param,
);

@ffi.Native<
        ffi.Int Function(ffi.Pointer<pthread_attr_t>, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_attr_getschedpolicy', assetId: 'mediator-bindings')
external int pthread_attr_getschedpolicy(
  ffi.Pointer<pthread_attr_t> __attr,
  ffi.Pointer<ffi.Int> __policy,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_attr_t>, ffi.Int)>(
    symbol: 'pthread_attr_setschedpolicy', assetId: 'mediator-bindings')
external int pthread_attr_setschedpolicy(
  ffi.Pointer<pthread_attr_t> __attr,
  int __policy,
);

@ffi.Native<
        ffi.Int Function(ffi.Pointer<pthread_attr_t>, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_attr_getinheritsched', assetId: 'mediator-bindings')
external int pthread_attr_getinheritsched(
  ffi.Pointer<pthread_attr_t> __attr,
  ffi.Pointer<ffi.Int> __inherit,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_attr_t>, ffi.Int)>(
    symbol: 'pthread_attr_setinheritsched', assetId: 'mediator-bindings')
external int pthread_attr_setinheritsched(
  ffi.Pointer<pthread_attr_t> __attr,
  int __inherit,
);

@ffi.Native<
        ffi.Int Function(ffi.Pointer<pthread_attr_t>, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_attr_getscope', assetId: 'mediator-bindings')
external int pthread_attr_getscope(
  ffi.Pointer<pthread_attr_t> __attr,
  ffi.Pointer<ffi.Int> __scope,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_attr_t>, ffi.Int)>(
    symbol: 'pthread_attr_setscope', assetId: 'mediator-bindings')
external int pthread_attr_setscope(
  ffi.Pointer<pthread_attr_t> __attr,
  int __scope,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_attr_t>, ffi.Pointer<ffi.Pointer<ffi.Void>>)>(
    symbol: 'pthread_attr_getstackaddr', assetId: 'mediator-bindings')
external int pthread_attr_getstackaddr(
  ffi.Pointer<pthread_attr_t> __attr,
  ffi.Pointer<ffi.Pointer<ffi.Void>> __stackaddr,
);

@ffi.Native<
        ffi.Int Function(ffi.Pointer<pthread_attr_t>, ffi.Pointer<ffi.Void>)>(
    symbol: 'pthread_attr_setstackaddr', assetId: 'mediator-bindings')
external int pthread_attr_setstackaddr(
  ffi.Pointer<pthread_attr_t> __attr,
  ffi.Pointer<ffi.Void> __stackaddr,
);

@ffi.Native<
        ffi.Int Function(ffi.Pointer<pthread_attr_t>, ffi.Pointer<ffi.Size>)>(
    symbol: 'pthread_attr_getstacksize', assetId: 'mediator-bindings')
external int pthread_attr_getstacksize(
  ffi.Pointer<pthread_attr_t> __attr,
  ffi.Pointer<ffi.Size> __stacksize,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_attr_t>, ffi.Size)>(
    symbol: 'pthread_attr_setstacksize', assetId: 'mediator-bindings')
external int pthread_attr_setstacksize(
  ffi.Pointer<pthread_attr_t> __attr,
  int __stacksize,
);

@ffi.Native<
        ffi.Int Function(ffi.Pointer<pthread_attr_t>,
            ffi.Pointer<ffi.Pointer<ffi.Void>>, ffi.Pointer<ffi.Size>)>(
    symbol: 'pthread_attr_getstack', assetId: 'mediator-bindings')
external int pthread_attr_getstack(
  ffi.Pointer<pthread_attr_t> __attr,
  ffi.Pointer<ffi.Pointer<ffi.Void>> __stackaddr,
  ffi.Pointer<ffi.Size> __stacksize,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_attr_t>, ffi.Pointer<ffi.Void>, ffi.Size)>(
    symbol: 'pthread_attr_setstack', assetId: 'mediator-bindings')
external int pthread_attr_setstack(
  ffi.Pointer<pthread_attr_t> __attr,
  ffi.Pointer<ffi.Void> __stackaddr,
  int __stacksize,
);

@ffi.Native<ffi.Int Function(pthread_t, ffi.Int, ffi.Pointer<sched_param>)>(
    symbol: 'pthread_setschedparam', assetId: 'mediator-bindings')
external int pthread_setschedparam(
  int __target_thread,
  int __policy,
  ffi.Pointer<sched_param> __param,
);

@ffi.Native<
        ffi.Int Function(
            pthread_t, ffi.Pointer<ffi.Int>, ffi.Pointer<sched_param>)>(
    symbol: 'pthread_getschedparam', assetId: 'mediator-bindings')
external int pthread_getschedparam(
  int __target_thread,
  ffi.Pointer<ffi.Int> __policy,
  ffi.Pointer<sched_param> __param,
);

@ffi.Native<ffi.Int Function(pthread_t, ffi.Int)>(
    symbol: 'pthread_setschedprio', assetId: 'mediator-bindings')
external int pthread_setschedprio(
  int __target_thread,
  int __prio,
);

@ffi.Native<
        ffi.Int Function(ffi.Pointer<pthread_once_t>,
            ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>)>(
    symbol: 'pthread_once', assetId: 'mediator-bindings')
external int pthread_once(
  ffi.Pointer<pthread_once_t> __once_control,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> __init_routine,
);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_setcancelstate', assetId: 'mediator-bindings')
external int pthread_setcancelstate(
  int __state,
  ffi.Pointer<ffi.Int> __oldstate,
);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_setcanceltype', assetId: 'mediator-bindings')
external int pthread_setcanceltype(
  int __type,
  ffi.Pointer<ffi.Int> __oldtype,
);

@ffi.Native<ffi.Int Function(pthread_t)>(
    symbol: 'pthread_cancel', assetId: 'mediator-bindings')
external int pthread_cancel(
  int __th,
);

@ffi.Native<ffi.Void Function()>(
    symbol: 'pthread_testcancel', assetId: 'mediator-bindings')
external void pthread_testcancel();

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_mutex_t>, ffi.Pointer<pthread_mutexattr_t>)>(
    symbol: 'pthread_mutex_init', assetId: 'mediator-bindings')
external int pthread_mutex_init(
  ffi.Pointer<pthread_mutex_t> __mutex,
  ffi.Pointer<pthread_mutexattr_t> __mutexattr,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_mutex_t>)>(
    symbol: 'pthread_mutex_destroy', assetId: 'mediator-bindings')
external int pthread_mutex_destroy(
  ffi.Pointer<pthread_mutex_t> __mutex,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_mutex_t>)>(
    symbol: 'pthread_mutex_trylock', assetId: 'mediator-bindings')
external int pthread_mutex_trylock(
  ffi.Pointer<pthread_mutex_t> __mutex,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_mutex_t>)>(
    symbol: 'pthread_mutex_lock', assetId: 'mediator-bindings')
external int pthread_mutex_lock(
  ffi.Pointer<pthread_mutex_t> __mutex,
);

@ffi.Native<
        ffi.Int Function(ffi.Pointer<pthread_mutex_t>, ffi.Pointer<timespec>)>(
    symbol: 'pthread_mutex_timedlock', assetId: 'mediator-bindings')
external int pthread_mutex_timedlock(
  ffi.Pointer<pthread_mutex_t> __mutex,
  ffi.Pointer<timespec> __abstime,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_mutex_t>)>(
    symbol: 'pthread_mutex_unlock', assetId: 'mediator-bindings')
external int pthread_mutex_unlock(
  ffi.Pointer<pthread_mutex_t> __mutex,
);

@ffi.Native<
        ffi.Int Function(ffi.Pointer<pthread_mutex_t>, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_mutex_getprioceiling', assetId: 'mediator-bindings')
external int pthread_mutex_getprioceiling(
  ffi.Pointer<pthread_mutex_t> __mutex,
  ffi.Pointer<ffi.Int> __prioceiling,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_mutex_t>, ffi.Int, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_mutex_setprioceiling', assetId: 'mediator-bindings')
external int pthread_mutex_setprioceiling(
  ffi.Pointer<pthread_mutex_t> __mutex,
  int __prioceiling,
  ffi.Pointer<ffi.Int> __old_ceiling,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_mutex_t>)>(
    symbol: 'pthread_mutex_consistent', assetId: 'mediator-bindings')
external int pthread_mutex_consistent(
  ffi.Pointer<pthread_mutex_t> __mutex,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_mutexattr_t>)>(
    symbol: 'pthread_mutexattr_init', assetId: 'mediator-bindings')
external int pthread_mutexattr_init(
  ffi.Pointer<pthread_mutexattr_t> __attr,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_mutexattr_t>)>(
    symbol: 'pthread_mutexattr_destroy', assetId: 'mediator-bindings')
external int pthread_mutexattr_destroy(
  ffi.Pointer<pthread_mutexattr_t> __attr,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_mutexattr_t>, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_mutexattr_getpshared', assetId: 'mediator-bindings')
external int pthread_mutexattr_getpshared(
  ffi.Pointer<pthread_mutexattr_t> __attr,
  ffi.Pointer<ffi.Int> __pshared,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_mutexattr_t>, ffi.Int)>(
    symbol: 'pthread_mutexattr_setpshared', assetId: 'mediator-bindings')
external int pthread_mutexattr_setpshared(
  ffi.Pointer<pthread_mutexattr_t> __attr,
  int __pshared,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_mutexattr_t>, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_mutexattr_gettype', assetId: 'mediator-bindings')
external int pthread_mutexattr_gettype(
  ffi.Pointer<pthread_mutexattr_t> __attr,
  ffi.Pointer<ffi.Int> __kind,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_mutexattr_t>, ffi.Int)>(
    symbol: 'pthread_mutexattr_settype', assetId: 'mediator-bindings')
external int pthread_mutexattr_settype(
  ffi.Pointer<pthread_mutexattr_t> __attr,
  int __kind,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_mutexattr_t>, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_mutexattr_getprotocol', assetId: 'mediator-bindings')
external int pthread_mutexattr_getprotocol(
  ffi.Pointer<pthread_mutexattr_t> __attr,
  ffi.Pointer<ffi.Int> __protocol,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_mutexattr_t>, ffi.Int)>(
    symbol: 'pthread_mutexattr_setprotocol', assetId: 'mediator-bindings')
external int pthread_mutexattr_setprotocol(
  ffi.Pointer<pthread_mutexattr_t> __attr,
  int __protocol,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_mutexattr_t>, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_mutexattr_getprioceiling', assetId: 'mediator-bindings')
external int pthread_mutexattr_getprioceiling(
  ffi.Pointer<pthread_mutexattr_t> __attr,
  ffi.Pointer<ffi.Int> __prioceiling,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_mutexattr_t>, ffi.Int)>(
    symbol: 'pthread_mutexattr_setprioceiling', assetId: 'mediator-bindings')
external int pthread_mutexattr_setprioceiling(
  ffi.Pointer<pthread_mutexattr_t> __attr,
  int __prioceiling,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_mutexattr_t>, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_mutexattr_getrobust', assetId: 'mediator-bindings')
external int pthread_mutexattr_getrobust(
  ffi.Pointer<pthread_mutexattr_t> __attr,
  ffi.Pointer<ffi.Int> __robustness,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_mutexattr_t>, ffi.Int)>(
    symbol: 'pthread_mutexattr_setrobust', assetId: 'mediator-bindings')
external int pthread_mutexattr_setrobust(
  ffi.Pointer<pthread_mutexattr_t> __attr,
  int __robustness,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_rwlock_t>, ffi.Pointer<pthread_rwlockattr_t>)>(
    symbol: 'pthread_rwlock_init', assetId: 'mediator-bindings')
external int pthread_rwlock_init(
  ffi.Pointer<pthread_rwlock_t> __rwlock,
  ffi.Pointer<pthread_rwlockattr_t> __attr,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_rwlock_t>)>(
    symbol: 'pthread_rwlock_destroy', assetId: 'mediator-bindings')
external int pthread_rwlock_destroy(
  ffi.Pointer<pthread_rwlock_t> __rwlock,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_rwlock_t>)>(
    symbol: 'pthread_rwlock_rdlock', assetId: 'mediator-bindings')
external int pthread_rwlock_rdlock(
  ffi.Pointer<pthread_rwlock_t> __rwlock,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_rwlock_t>)>(
    symbol: 'pthread_rwlock_tryrdlock', assetId: 'mediator-bindings')
external int pthread_rwlock_tryrdlock(
  ffi.Pointer<pthread_rwlock_t> __rwlock,
);

@ffi.Native<
        ffi.Int Function(ffi.Pointer<pthread_rwlock_t>, ffi.Pointer<timespec>)>(
    symbol: 'pthread_rwlock_timedrdlock', assetId: 'mediator-bindings')
external int pthread_rwlock_timedrdlock(
  ffi.Pointer<pthread_rwlock_t> __rwlock,
  ffi.Pointer<timespec> __abstime,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_rwlock_t>)>(
    symbol: 'pthread_rwlock_wrlock', assetId: 'mediator-bindings')
external int pthread_rwlock_wrlock(
  ffi.Pointer<pthread_rwlock_t> __rwlock,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_rwlock_t>)>(
    symbol: 'pthread_rwlock_trywrlock', assetId: 'mediator-bindings')
external int pthread_rwlock_trywrlock(
  ffi.Pointer<pthread_rwlock_t> __rwlock,
);

@ffi.Native<
        ffi.Int Function(ffi.Pointer<pthread_rwlock_t>, ffi.Pointer<timespec>)>(
    symbol: 'pthread_rwlock_timedwrlock', assetId: 'mediator-bindings')
external int pthread_rwlock_timedwrlock(
  ffi.Pointer<pthread_rwlock_t> __rwlock,
  ffi.Pointer<timespec> __abstime,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_rwlock_t>)>(
    symbol: 'pthread_rwlock_unlock', assetId: 'mediator-bindings')
external int pthread_rwlock_unlock(
  ffi.Pointer<pthread_rwlock_t> __rwlock,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_rwlockattr_t>)>(
    symbol: 'pthread_rwlockattr_init', assetId: 'mediator-bindings')
external int pthread_rwlockattr_init(
  ffi.Pointer<pthread_rwlockattr_t> __attr,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_rwlockattr_t>)>(
    symbol: 'pthread_rwlockattr_destroy', assetId: 'mediator-bindings')
external int pthread_rwlockattr_destroy(
  ffi.Pointer<pthread_rwlockattr_t> __attr,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_rwlockattr_t>, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_rwlockattr_getpshared', assetId: 'mediator-bindings')
external int pthread_rwlockattr_getpshared(
  ffi.Pointer<pthread_rwlockattr_t> __attr,
  ffi.Pointer<ffi.Int> __pshared,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_rwlockattr_t>, ffi.Int)>(
    symbol: 'pthread_rwlockattr_setpshared', assetId: 'mediator-bindings')
external int pthread_rwlockattr_setpshared(
  ffi.Pointer<pthread_rwlockattr_t> __attr,
  int __pshared,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_rwlockattr_t>, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_rwlockattr_getkind_np', assetId: 'mediator-bindings')
external int pthread_rwlockattr_getkind_np(
  ffi.Pointer<pthread_rwlockattr_t> __attr,
  ffi.Pointer<ffi.Int> __pref,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_rwlockattr_t>, ffi.Int)>(
    symbol: 'pthread_rwlockattr_setkind_np', assetId: 'mediator-bindings')
external int pthread_rwlockattr_setkind_np(
  ffi.Pointer<pthread_rwlockattr_t> __attr,
  int __pref,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_cond_t>, ffi.Pointer<pthread_condattr_t>)>(
    symbol: 'pthread_cond_init', assetId: 'mediator-bindings')
external int pthread_cond_init(
  ffi.Pointer<pthread_cond_t> __cond,
  ffi.Pointer<pthread_condattr_t> __cond_attr,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_cond_t>)>(
    symbol: 'pthread_cond_destroy', assetId: 'mediator-bindings')
external int pthread_cond_destroy(
  ffi.Pointer<pthread_cond_t> __cond,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_cond_t>)>(
    symbol: 'pthread_cond_signal', assetId: 'mediator-bindings')
external int pthread_cond_signal(
  ffi.Pointer<pthread_cond_t> __cond,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_cond_t>)>(
    symbol: 'pthread_cond_broadcast', assetId: 'mediator-bindings')
external int pthread_cond_broadcast(
  ffi.Pointer<pthread_cond_t> __cond,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_cond_t>, ffi.Pointer<pthread_mutex_t>)>(
    symbol: 'pthread_cond_wait', assetId: 'mediator-bindings')
external int pthread_cond_wait(
  ffi.Pointer<pthread_cond_t> __cond,
  ffi.Pointer<pthread_mutex_t> __mutex,
);

@ffi.Native<
        ffi.Int Function(ffi.Pointer<pthread_cond_t>,
            ffi.Pointer<pthread_mutex_t>, ffi.Pointer<timespec>)>(
    symbol: 'pthread_cond_timedwait', assetId: 'mediator-bindings')
external int pthread_cond_timedwait(
  ffi.Pointer<pthread_cond_t> __cond,
  ffi.Pointer<pthread_mutex_t> __mutex,
  ffi.Pointer<timespec> __abstime,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_condattr_t>)>(
    symbol: 'pthread_condattr_init', assetId: 'mediator-bindings')
external int pthread_condattr_init(
  ffi.Pointer<pthread_condattr_t> __attr,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_condattr_t>)>(
    symbol: 'pthread_condattr_destroy', assetId: 'mediator-bindings')
external int pthread_condattr_destroy(
  ffi.Pointer<pthread_condattr_t> __attr,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_condattr_t>, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_condattr_getpshared', assetId: 'mediator-bindings')
external int pthread_condattr_getpshared(
  ffi.Pointer<pthread_condattr_t> __attr,
  ffi.Pointer<ffi.Int> __pshared,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_condattr_t>, ffi.Int)>(
    symbol: 'pthread_condattr_setpshared', assetId: 'mediator-bindings')
external int pthread_condattr_setpshared(
  ffi.Pointer<pthread_condattr_t> __attr,
  int __pshared,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_condattr_t>, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_condattr_getclock', assetId: 'mediator-bindings')
external int pthread_condattr_getclock(
  ffi.Pointer<pthread_condattr_t> __attr,
  ffi.Pointer<ffi.Int> __clock_id,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_condattr_t>, ffi.Int)>(
    symbol: 'pthread_condattr_setclock', assetId: 'mediator-bindings')
external int pthread_condattr_setclock(
  ffi.Pointer<pthread_condattr_t> __attr,
  int __clock_id,
);

@ffi.Native<
        ffi.Int Function(ffi.Pointer<pthread_barrier_t>,
            ffi.Pointer<pthread_barrierattr_t>, ffi.UnsignedInt)>(
    symbol: 'pthread_barrier_init', assetId: 'mediator-bindings')
external int pthread_barrier_init(
  ffi.Pointer<pthread_barrier_t> __barrier,
  ffi.Pointer<pthread_barrierattr_t> __attr,
  int __count,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_barrier_t>)>(
    symbol: 'pthread_barrier_destroy', assetId: 'mediator-bindings')
external int pthread_barrier_destroy(
  ffi.Pointer<pthread_barrier_t> __barrier,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_barrier_t>)>(
    symbol: 'pthread_barrier_wait', assetId: 'mediator-bindings')
external int pthread_barrier_wait(
  ffi.Pointer<pthread_barrier_t> __barrier,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_barrierattr_t>)>(
    symbol: 'pthread_barrierattr_init', assetId: 'mediator-bindings')
external int pthread_barrierattr_init(
  ffi.Pointer<pthread_barrierattr_t> __attr,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_barrierattr_t>)>(
    symbol: 'pthread_barrierattr_destroy', assetId: 'mediator-bindings')
external int pthread_barrierattr_destroy(
  ffi.Pointer<pthread_barrierattr_t> __attr,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_barrierattr_t>, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_barrierattr_getpshared', assetId: 'mediator-bindings')
external int pthread_barrierattr_getpshared(
  ffi.Pointer<pthread_barrierattr_t> __attr,
  ffi.Pointer<ffi.Int> __pshared,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<pthread_barrierattr_t>, ffi.Int)>(
    symbol: 'pthread_barrierattr_setpshared', assetId: 'mediator-bindings')
external int pthread_barrierattr_setpshared(
  ffi.Pointer<pthread_barrierattr_t> __attr,
  int __pshared,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<pthread_key_t>,
            ffi.Pointer<
                ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>)>(
    symbol: 'pthread_key_create', assetId: 'mediator-bindings')
external int pthread_key_create(
  ffi.Pointer<pthread_key_t> __key,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>
      __destr_function,
);

@ffi.Native<ffi.Int Function(pthread_key_t)>(
    symbol: 'pthread_key_delete', assetId: 'mediator-bindings')
external int pthread_key_delete(
  int __key,
);

@ffi.Native<ffi.Pointer<ffi.Void> Function(pthread_key_t)>(
    symbol: 'pthread_getspecific', assetId: 'mediator-bindings')
external ffi.Pointer<ffi.Void> pthread_getspecific(
  int __key,
);

@ffi.Native<ffi.Int Function(pthread_key_t, ffi.Pointer<ffi.Void>)>(
    symbol: 'pthread_setspecific', assetId: 'mediator-bindings')
external int pthread_setspecific(
  int __key,
  ffi.Pointer<ffi.Void> __pointer,
);

@ffi.Native<ffi.Int Function(pthread_t, ffi.Pointer<ffi.Int>)>(
    symbol: 'pthread_getcpuclockid', assetId: 'mediator-bindings')
external int pthread_getcpuclockid(
  int __thread_id,
  ffi.Pointer<ffi.Int> __clock_id,
);

@ffi.Native<
        ffi.Int Function(
            ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>,
            ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>,
            ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>)>(
    symbol: 'pthread_atfork', assetId: 'mediator-bindings')
external int pthread_atfork(
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> __prepare,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> __parent,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> __child,
);

@ffi.Native<
        ffi.Bool Function(ffi.Pointer<mediator_dart_notifier>,
            ffi.Pointer<mediator_dart_notifier_configuration>)>(
    symbol: 'mediator_dart_notifier_initialize',
    assetId: 'mediator-bindings',
    isLeaf: true)
external bool mediator_dart_notifier_initialize(
  ffi.Pointer<mediator_dart_notifier> notifier,
  ffi.Pointer<mediator_dart_notifier_configuration> configuration,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<mediator_dart_notifier>)>(
    symbol: 'mediator_dart_notifier_shutdown',
    assetId: 'mediator-bindings',
    isLeaf: true)
external bool mediator_dart_notifier_shutdown(
  ffi.Pointer<mediator_dart_notifier> notifier,
);

@ffi.Native<
        ffi.Int32 Function(
            ffi.Pointer<mediator_dart>,
            ffi.Pointer<mediator_dart_configuration>,
            ffi.Pointer<mediator_dart_notifier>)>(
    symbol: 'mediator_dart_initialize',
    assetId: 'mediator-bindings',
    isLeaf: true)
external int mediator_dart_initialize(
  ffi.Pointer<mediator_dart> mediator,
  ffi.Pointer<mediator_dart_configuration> configuration,
  ffi.Pointer<mediator_dart_notifier> notifier,
);

@ffi.Native<
        ffi.Void Function(
            ffi.Pointer<mediator_dart>, mediator_notify_callback)>(
    symbol: 'mediator_dart_setup', assetId: 'mediator-bindings', isLeaf: true)
external void mediator_dart_setup(
  ffi.Pointer<mediator_dart> mediator,
  mediator_notify_callback callback,
);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<mediator_dart>)>(
    symbol: 'mediator_dart_peek', assetId: 'mediator-bindings', isLeaf: true)
external int mediator_dart_peek(
  ffi.Pointer<mediator_dart> mediator,
);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<mediator_dart>)>(
    symbol: 'mediator_dart_peek_wait',
    assetId: 'mediator-bindings',
    isLeaf: true)
external int mediator_dart_peek_wait(
  ffi.Pointer<mediator_dart> mediator,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<mediator_dart>)>(
    symbol: 'mediator_dart_submit', assetId: 'mediator-bindings', isLeaf: true)
external void mediator_dart_submit(
  ffi.Pointer<mediator_dart> mediator,
);

@ffi.Native<
        ffi.Void Function(ffi.Pointer<mediator_dart>, ffi.Int32,
            ffi.Pointer<mediator_message>)>(
    symbol: 'mediator_dart_call_native',
    assetId: 'mediator-bindings',
    isLeaf: true)
external void mediator_dart_call_native(
  ffi.Pointer<mediator_dart> mediator,
  int target_ring_fd,
  ffi.Pointer<mediator_message> message,
);

@ffi.Native<
        ffi.Void Function(
            ffi.Pointer<mediator_dart>, ffi.Pointer<mediator_message>)>(
    symbol: 'mediator_dart_callback_to_native',
    assetId: 'mediator-bindings',
    isLeaf: true)
external void mediator_dart_callback_to_native(
  ffi.Pointer<mediator_dart> mediator,
  ffi.Pointer<mediator_message> message,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<mediator_dart>, ffi.Int32)>(
    symbol: 'mediator_dart_completion_advance',
    assetId: 'mediator-bindings',
    isLeaf: true)
external void mediator_dart_completion_advance(
  ffi.Pointer<mediator_dart> mediator,
  int count,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<mediator_dart>)>(
    symbol: 'mediator_dart_destroy', assetId: 'mediator-bindings', isLeaf: true)
external void mediator_dart_destroy(
  ffi.Pointer<mediator_dart> mediator,
);

final class mediator_dart_configuration extends ffi.Struct {
  @ffi.Size()
  external int quota_size;

  @ffi.Size()
  external int preallocation_size;

  @ffi.Size()
  external int slab_size;

  @ffi.Size()
  external int static_buffers_capacity;

  @ffi.Size()
  external int static_buffer_size;

  @ffi.Size()
  external int ring_size;

  @ffi.Uint64()
  external int maximum_waking_time_millis;

  @ffi.Uint64()
  external int completion_wait_timeout_millis;

  @ffi.Uint32()
  external int ring_flags;

  @ffi.Uint32()
  external int completion_wait_count;

  @ffi.Uint32()
  external int completion_peek_count;

  @ffi.Bool()
  external bool trace;
}

final class mediator_module_native_configuration extends ffi.Struct {
  @ffi.Uint64()
  external int completion_wait_timeout_millis;

  @ffi.Size()
  external int quota_size;

  @ffi.Size()
  external int preallocation_size;

  @ffi.Size()
  external int slab_size;

  @ffi.Size()
  external int static_buffers_capacity;

  @ffi.Size()
  external int static_buffer_size;

  @ffi.Size()
  external int ring_size;

  @ffi.Int32()
  external int ring_flags;

  @ffi.Uint32()
  external int completion_wait_count;
}

final class mediator_message extends ffi.Struct {
  @ffi.Uint64()
  external int id;

  @ffi.Uint64()
  external int source;

  @ffi.Uint64()
  external int target;

  @ffi.Uint64()
  external int owner;

  @ffi.Uint64()
  external int method;

  external ffi.Pointer<ffi.Void> input;

  @ffi.Size()
  external int input_size;

  external ffi.Pointer<ffi.Void> output;

  @ffi.Size()
  external int output_size;

  @ffi.Uint16()
  external int flags;
}

final class mediator_completion_event extends ffi.Struct {
  @ffi.UnsignedLongLong()
  external int user_data;

  @ffi.Int()
  external int res;

  @ffi.UnsignedInt()
  external int flags;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedLongLong> big_cqe;
}

final class timespec extends ffi.Struct {
  @ffi.Long()
  external int tv_sec;

  @ffi.Long()
  external int tv_nsec;
}

final class sched_param extends ffi.Struct {
  @ffi.Int()
  external int sched_priority;
}

final class cpu_set_t extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.UnsignedLong> __bits;
}

final class tm extends ffi.Struct {
  @ffi.Int()
  external int tm_sec;

  @ffi.Int()
  external int tm_min;

  @ffi.Int()
  external int tm_hour;

  @ffi.Int()
  external int tm_mday;

  @ffi.Int()
  external int tm_mon;

  @ffi.Int()
  external int tm_year;

  @ffi.Int()
  external int tm_wday;

  @ffi.Int()
  external int tm_yday;

  @ffi.Int()
  external int tm_isdst;

  @ffi.Long()
  external int tm_gmtoff;

  external ffi.Pointer<ffi.Char> tm_zone;
}

final class itimerspec extends ffi.Struct {
  external timespec it_interval;

  external timespec it_value;
}

final class sigevent extends ffi.Opaque {}

typedef clock_t = ffi.Long;
typedef Dartclock_t = int;
typedef time_t = ffi.Long;
typedef Darttime_t = int;
typedef locale_t = ffi.Pointer<__locale_struct>;

final class __locale_struct extends ffi.Struct {
  @ffi.Array.multi([13])
  external ffi.Array<ffi.Pointer<__locale_data>> __locales;

  external ffi.Pointer<ffi.UnsignedShort> __ctype_b;

  external ffi.Pointer<ffi.Int> __ctype_tolower;

  external ffi.Pointer<ffi.Int> __ctype_toupper;

  @ffi.Array.multi([13])
  external ffi.Array<ffi.Pointer<ffi.Char>> __names;
}

final class __locale_data extends ffi.Opaque {}

typedef clockid_t = ffi.Int;
typedef Dartclockid_t = int;
typedef pid_t = ffi.Int;
typedef Dartpid_t = int;
typedef timer_t = ffi.Pointer<ffi.Void>;

final class __atomic_wide_counter extends ffi.Union {
  @ffi.UnsignedLongLong()
  external int __value64;

  external UnnamedStruct1 __value32;
}

final class UnnamedStruct1 extends ffi.Struct {
  @ffi.UnsignedInt()
  external int __low;

  @ffi.UnsignedInt()
  external int __high;
}

final class pthread_mutexattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

final class pthread_condattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

final class pthread_attr_t extends ffi.Union {
  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_mutex_t extends ffi.Union {
  external __pthread_mutex_s __data;

  @ffi.Array.multi([40])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class __pthread_mutex_s extends ffi.Struct {
  @ffi.Int()
  external int __lock;

  @ffi.UnsignedInt()
  external int __count;

  @ffi.Int()
  external int __owner;

  @ffi.UnsignedInt()
  external int __nusers;

  @ffi.Int()
  external int __kind;

  @ffi.Short()
  external int __spins;

  @ffi.Short()
  external int __elision;

  external __pthread_internal_list __list;
}

final class __pthread_internal_list extends ffi.Struct {
  external ffi.Pointer<__pthread_internal_list> __prev;

  external ffi.Pointer<__pthread_internal_list> __next;
}

final class pthread_cond_t extends ffi.Union {
  external __pthread_cond_s __data;

  @ffi.Array.multi([48])
  external ffi.Array<ffi.Char> __size;

  @ffi.LongLong()
  external int __align;
}

final class __pthread_cond_s extends ffi.Struct {
  external __atomic_wide_counter __wseq;

  external __atomic_wide_counter __g1_start;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_refs;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_size;

  @ffi.UnsignedInt()
  external int __g1_orig_size;

  @ffi.UnsignedInt()
  external int __wrefs;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_signals;
}

final class pthread_rwlock_t extends ffi.Union {
  external __pthread_rwlock_arch_t __data;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class __pthread_rwlock_arch_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int __readers;

  @ffi.UnsignedInt()
  external int __writers;

  @ffi.UnsignedInt()
  external int __wrphase_futex;

  @ffi.UnsignedInt()
  external int __writers_futex;

  @ffi.UnsignedInt()
  external int __pad3;

  @ffi.UnsignedInt()
  external int __pad4;

  @ffi.Int()
  external int __cur_writer;

  @ffi.Int()
  external int __shared;

  @ffi.SignedChar()
  external int __rwelision;

  @ffi.Array.multi([7])
  external ffi.Array<ffi.UnsignedChar> __pad1;

  @ffi.UnsignedLong()
  external int __pad2;

  @ffi.UnsignedInt()
  external int __flags;
}

final class pthread_rwlockattr_t extends ffi.Union {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_barrier_t extends ffi.Union {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_barrierattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

typedef pthread_t = ffi.UnsignedLong;
typedef Dartpthread_t = int;
typedef pthread_once_t = ffi.Int;
typedef Dartpthread_once_t = int;
typedef pthread_key_t = ffi.UnsignedInt;
typedef Dartpthread_key_t = int;

final class io_uring extends ffi.Opaque {}

final class mediator_dart_notifier_configuration extends ffi.Struct {
  @ffi.Size()
  external int ring_size;

  @ffi.Size()
  external int ring_flags;

  @ffi.Uint64()
  external int initialization_timeout_seconds;

  @ffi.Uint64()
  external int shutdown_timeout_seconds;

  @ffi.Bool()
  external bool trace;
}

final class mediator_dart_notifier extends ffi.Struct {
  external mediator_dart_notifier_configuration configuration;

  external ffi.Pointer<ffi.Char> initialization_error;

  external ffi.Pointer<ffi.Char> shutdown_error;

  @pthread_t()
  external int main_thread_id;

  external pthread_mutex_t initialization_mutex;

  external pthread_cond_t initialization_condition;

  external pthread_mutex_t shutdown_mutex;

  external pthread_cond_t shutdown_condition;

  external ffi.Pointer<io_uring> ring;

  @ffi.Bool()
  external bool active;

  @ffi.Bool()
  external bool initialized;

  @ffi.Int32()
  external int descriptor;
}

final class io_uring_cqe extends ffi.Opaque {}

final class mediator_dart extends ffi.Struct {
  external mediator_notify_callback callback;

  external ffi.Pointer<mediator_dart_notifier> notifier;

  external ffi.Pointer<io_uring> ring;

  external ffi.Pointer<ffi.Pointer<mediator_dart_completion_event>> completions;

  external mediator_dart_configuration configuration;

  @ffi.Int32()
  external int descriptor;

  @ffi.Int8()
  external int state;
}

typedef mediator_notify_callback
    = ffi.Pointer<ffi.NativeFunction<mediator_notify_callbackFunction>>;
typedef mediator_notify_callbackFunction = ffi.Void Function();
typedef Dartmediator_notify_callbackFunction = void Function();
typedef mediator_dart_completion_event = io_uring_cqe;

const int PTHREAD_CREATE_JOINABLE = 0;

const int PTHREAD_CREATE_DETACHED = 1;

const int PTHREAD_MUTEX_TIMED_NP = 0;

const int PTHREAD_MUTEX_RECURSIVE_NP = 1;

const int PTHREAD_MUTEX_ERRORCHECK_NP = 2;

const int PTHREAD_MUTEX_ADAPTIVE_NP = 3;

const int PTHREAD_MUTEX_NORMAL = 0;

const int PTHREAD_MUTEX_RECURSIVE = 1;

const int PTHREAD_MUTEX_ERRORCHECK = 2;

const int PTHREAD_MUTEX_DEFAULT = 0;

const int PTHREAD_MUTEX_STALLED = 0;

const int PTHREAD_MUTEX_STALLED_NP = 0;

const int PTHREAD_MUTEX_ROBUST = 1;

const int PTHREAD_MUTEX_ROBUST_NP = 1;

const int PTHREAD_PRIO_NONE = 0;

const int PTHREAD_PRIO_INHERIT = 1;

const int PTHREAD_PRIO_PROTECT = 2;

const int PTHREAD_RWLOCK_PREFER_READER_NP = 0;

const int PTHREAD_RWLOCK_PREFER_WRITER_NP = 1;

const int PTHREAD_RWLOCK_PREFER_WRITER_NONRECURSIVE_NP = 2;

const int PTHREAD_RWLOCK_DEFAULT_NP = 0;

const int PTHREAD_INHERIT_SCHED = 0;

const int PTHREAD_EXPLICIT_SCHED = 1;

const int PTHREAD_SCOPE_SYSTEM = 0;

const int PTHREAD_SCOPE_PROCESS = 1;

const int PTHREAD_PROCESS_PRIVATE = 0;

const int PTHREAD_PROCESS_SHARED = 1;

const int PTHREAD_CANCEL_ENABLE = 0;

const int PTHREAD_CANCEL_DISABLE = 1;

const int PTHREAD_CANCEL_DEFERRED = 0;

const int PTHREAD_CANCEL_ASYNCHRONOUS = 1;
