name: core
version: 0.0.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dev_dependencies:
  ffigen: ^11.0.0

dependencies:
  ffi: ^2.1.0

ffigen:
  name: "CoreBindings"
  ffi-native:
    assetId: "core-bindings"
  description: "Bindings for core"
  output: "lib/core/bindings.dart"
  compiler-opts:
    - "-I../native/include"
  exclude-all-by-default: true
  headers:
    entry-points:
      - "../native/include/system/system.h"
  globals:
    exclude:
      - "(.*)"
  macros:
    exclude:
      - "(.*)"
  typedefs:
    exclude:
      - "_(.*)"
  functions:
    leaf:
      include:
        - "system_.*"
    include:
        - "system_.*"
    exclude:
      - "_(.*)"
  structs:
    exclude:
      - "_(.*)"
