name: reactive
version: 0.0.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.1.0"

dev_dependencies:
  test: ^1.24.6

dependencies:
  collection: ^1.18.0
  transport:
    path: ../transport/dart
  executor:
    path: ../executor/dart
  core:
    path: ../core/dart
  memory:
    path: ../memory/dart
