name: reactive
version: 0.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.1.0"

dependencies:
  test: ^1.22.0
  collection: ^1.18.0
  transport:
    path: ../transport/dart
  core:
    path: ../core/dart
