name: storage
publish_to: none
version: 0.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dev_dependencies:
  test: ^1.22.0

dependencies:
  ffi: ^2.1.0
  path: ^1.8.3
  memory:
    path: ../../memory/dart
  core:
    path: ../../core/dart
  executor:
    path: ../../executor/dart