name: storage
publish_to: none
version: 0.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dev_dependencies:
  ffigen: ^11.0.0
  test: ^1.22.0

dependencies:
  ffi: ^2.1.0
  path: ^1.8.3
  memory:
    path: ../../memory/dart
  core:
    path: ../../core/dart
  executor:
    path: ../../executor/dart

ffigen:
  name: "TarantoolBindings"
  ffi-native:
    assetId: "tarantool-bindings"
  description: "Bindings for Tarantool"
  output: "lib/storage/bindings.dart"
  headers:
    entry-points:
      - "../native/src/tarantool.h"
      - "../native/src/tarantool_executor.h"
      - "../native/src/tarantool_box.h"
      - "../native/src/tarantool_factory.h"
      - "../native/src/tarantool_tuple.h"
  globals:
    exclude:
      - "(.*)"
  macros:
    exclude:
      - "(.*)"
  typedefs:
    exclude:
      - "_(.*)"
  functions:
    leaf:
      include:
        - "tarantool_(.*)"
  structs:
    exclude:
      - "_(.*)"
      - "max_align_t"
  type-map:
    "structs":
      "executor_message":
        "lib": "executor"
        "c-type": "executor_message"
        "dart-type": "executor_message"
      "executor_completion_event":
        "lib": "executor"
        "c-type": "executor_completion_event"
        "dart-type": "executor_completion_event"
  library-imports:
    executor: "package:executor/executor.dart"
