name: interactor
version: 0.0.0
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dev_dependencies:
  ffigen: ^11.0.0

dependencies:
  ffi: ^2.1.0
  core:
    path:
      ../../core/dart

ffigen:
  name: "InteractorBindings"
  ffi-native:
    assetId: "interactor-bindings"
  description: "Bindings for Interactor"
  output: "lib/interactor/bindings.dart"
  compiler-opts:
    - "-I../native/include"
  headers:
    entry-points:
      - "../native/interactor_dart.h"
  globals:
    exclude:
      - "(.*)"
  macros:
    exclude:
      - "(.*)"
  typedefs:
    exclude:
      - "_(.*)"
  functions:
    leaf:
      include:
        - "interactor_dart_.*"
    exclude:
      - "_(.*)"
  structs:
    exclude:
      - "_(.*)"
      - "max_align_t"
      - "file_(.*)"
