// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_field
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Void Function(ffi.Int)>(
    symbol: 'system_dart_shutdown_descriptor',
    assetId: 'core-bindings',
    isLeaf: true)
external void system_dart_shutdown_descriptor(
  int fd,
);
