set(INTERACTOR_PATH "")
set(INTERACTOR_RESULT "")
set(INTERACTOR_DIRECTORY "")
set(INTERACTOR_LIBRARY "")

execute_process(
  COMMAND dart pub get
  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/dart
)

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
  execute_process(
    COMMAND dart run --define=DEBUG=true ../dart/bin/interactor.dart
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    RESULT_VARIABLE INTERACTOR_RESULT
    OUTPUT_VARIABLE INTERACTOR_PATH
  )
else()
  execute_process(
    COMMAND dart run ../dart/bin/interactor.dart
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    RESULT_VARIABLE INTERACTOR_RESULT
    OUTPUT_VARIABLE INTERACTOR_PATH
  )
endif()

cmake_path(GET INTERACTOR_PATH PARENT_PATH INTERACTOR_DIRECTORY)
string(REPLACE "\n" "" INTERACTOR_LIBRARY "${INTERACTOR_PATH}")
set(INTERACTOR_INCLUDE_DIRECTORY ${INTERACTOR_DIRECTORY}/../../native/include)